name: azure-devops-pulumi-oidc-ci-cd
description: Basics for Provisioning OIDC trusts between Azure DevOps and Azure cloud
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: azure-typescript
packages:
  azure-agents:
    source: terraform-module
    version: 0.1.8
    parameters:
      - Azure/avm-ptn-cicd-agents-and-runners/azurerm
      - 0.4.0
      - azure-agents
