// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ContainerAppEnvironmentVariablesArgs {
    name?: pulumi.Input<string>;
    value?: pulumi.Input<string>;
}

export interface ContainerAppSensitiveEnvironmentVariablesArgs {
    container_app_secret_name?: pulumi.Input<string>;
    keda_auth_name?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    value?: pulumi.Input<string>;
}

export interface ContainerInstanceEnvironmentVariablesArgs {
    name?: pulumi.Input<string>;
    value?: pulumi.Input<string>;
}

export interface ContainerInstanceSensitiveEnvironmentVariablesArgs {
    name?: pulumi.Input<string>;
    value?: pulumi.Input<string>;
}

export interface CustomContainerRegistryImagesArgs {
    context_access_token?: pulumi.Input<string>;
    context_path?: pulumi.Input<string>;
    dockerfile_path?: pulumi.Input<string>;
    image_names?: pulumi.Input<pulumi.Input<string>[]>;
    task_name?: pulumi.Input<string>;
}

export interface DelaysArgs {
    delay_after_container_app_environment_creation?: pulumi.Input<number>;
    delay_after_container_image_build?: pulumi.Input<number>;
}

export interface LockArgs {
    kind?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
}
